### PR TITLE
Allow DOM/jQuery objects from title callback

### PR DESCRIPTION
**Pull request by jsor**
This allows something like:

```
$('#example').tipsy({
    title: function() {
        var tip = $('<span>Loading...</span>');

        $.getJSON('http://example.com/data.json', function(data) {
            tip.text(data.title);
        });

        return tip;
    }
});
```

### CODE REVIEW

**Comment by gdpotter** [comment]
+1 This would be really nice.

**Comment by pokonski** [comment]
There's been no activity since September :(

**Comment by gdpotter** [comment]
Yeah, it's too bad.  I have my own frankensteined tipsy right now with three forks which are currently pull requests.

**Comment by thegrandpoobah** [comment]
Maybe @jaz303 can comment on what his intentions are? Maybe he has just grown bored with the project, or doesn't have time to "baby-sit" it. If so, maybe he can put tipsy up for adoption and let somebody else maintain it. There are a _lot_ of pull requests with great ideas waiting in the wing...

If jaz doesn't respond, maybe it would be time to make one of the many many fork a "semi-official" one with the pull requests merged in?

Just some ideas.

**Comment by henrik** [comment]
Twitter Bootstrap has [Twipsy](http://twitter.github.com/bootstrap/javascript.html#twipsy), based on Tipsy – maybe they're receptive.

**Comment by julien-c** [comment]
Link to the Github repo for Twipsy: https://github.com/twitter/bootstrap/blob/master/js/bootstrap-twipsy.js

**Comment by pokonski** [comment]
True, Bootstrap is maintained just fine.

**Pull request closed without merging**
