### PR TITLE
Reformatted README as markdown so it displays nicely on github.

### PR DESCRIPTION
**Pull request by twe4ked**
Cheers

### CODE REVIEW

**Comment by timoxley** [comment]
+1

**Comment by chrisjacob** [comment]
+1

**Comment by pokonski** [comment]
Huh, didn't notice that before reformatting it myself :D

**Comment by twe4ked** [comment]
Now we play the waiting game :-)

**Comment by jaz303** [comment]
Oops sorry didn't see this one, someone else submitted a pull request for a similar thing and I merged it already. Thank you for this.

**Pull request closed without merging**
