### PR TITLE
One pull request to end them all

### PR DESCRIPTION
**Pull request by CloCkWeRX**
This merges multiple patches from forks on github.

Specifically: 
Style (trailing spaces) has been fixed by multiple parties
on() vs live() in newer versions of jquery
Fixes to SVG behaviour (use of getBBox())
Ability to inject a custom css class
... and more.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
(As an alternative, I'm happy to take over the maintenance of tipsy)

**Comment by MoOx** [comment]
:100: \* :100:
Seriously @jaz303, you should do something. Close all PR or give this project to somebody... At least do something...

**Comment by notslang** [comment]
+1 ... I would love to see this project continue to be maintained. If @jaz303 doesn't have time to deal with it, he should pass it on to someone else.

**Comment by ghost** [comment]
Can't just somebody rename it and make this project kind of his own (based on jaz303 tipsy of course) since it's already open source?

**Comment by MoOx** [comment]
Just use this related fork... https://github.com/CloCkWeRX/tipsy
But it's sure that's a shame that @jaz303 doesn't take five minutes to do something...

**Comment by jaz303** [comment]
Gonna review each of the commits in this PR and merge them over the next couple of hours.

**Comment by notslang** [comment]
@jaz303 So... did that reviewing of the commits happen?

**Comment by MoOx** [comment]
:8ball:

**Comment by tcigrand** [comment]
Did anything ever happen with this?

It seems like @CloCkWeRX has a pretty update to date version, but https://github.com/MartinMartimeo/tipsy is the version on cdnjs.com/libraries/jquery.tipsy and https://www.npmjs.com/package/jquery.tipsy.

It would be great to have some more organization on this.

**Comment by CloCkWeRX** [comment]
Going to close this, because the maintainer is too lazy to do end of life duties

**Pull request closed without merging**
